import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import "../styles/globals.scss"

import * as React from 'react';

// const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="initial-scale=1, width=device-width" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
